# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/centos8"
  config.vm.hostname = "centos8n5"
  # config.vm.base_address = "192.168.56.8"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 5608, host_ip: "127.0.0.1"
  # config.vm.network "forwarded_port", guest: 80, host: 5608

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.56.5"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"
  # config.vm.network "public_network", use_dhcp_assigned_default_route: true
  config.vm.network "public_network", ip: "192.168.0.5", bridge: "wlo1"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Disable the default share of the current code directory. Doing this
  # provides improved isolation between the vagrant box and your host
  # by making sure your Vagrantfile isn't accessible to the vagrant box.
  # If you use this you may want to enable additional shared subfolders as
  # shown above.
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "/home/rusman/Documents/vagrant", "/home/vagrant/"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.name = "centos8n5"
    vb.memory = 10240
    vb.cpus = 8
    # Display the VirtualBox GUI when booting the machine
    # vb.gui = true
  
    # Customize the amount of memory on the VM:
    # vb.memory = "1024"
  end

  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    sudo dnf update -y
    # # sudo dnf install -y https://extras.getpagespeed.com/release-latest.rpm
    sudo dnf -y module reset nginx
    sudo dnf -y module enable nginx:1.22
    sudo dnf install -y firewall-config nano nginx
    sudo systemctl enable nginx
    sudo systemctl restart nginx
    sudo firewall-cmd --add-service http

    sudo dnf install -y centos-release-stream
    sudo dnf -y swap centos-{linux,stream}-repos
    sudo dnf -y distro-sync
    sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    sudo dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    sudo dnf install yum-utils
    sudo dnf -y module reset php
    sudo dnf -y module enable php:remi-8.3
    sudo dnf upgrade -y
    # sudo dnf install -y php php-cli php-common php-fpm php-mysql php-pdo php-mbstring php-gd php-imagick php-bcmath php-curl php-devel php-intl php-ldap php-pgsql php-redis php-uploadprogress php-xdebug php-zip php-dom php-odbc
    # sudo dnf install -y php81 php81-php-cli php81-php-common php81-php-fpm php81-php-mysql php81-php-pdo php81-php-mbstring php81-php-gd php81-php-imagick php81-php-bcmath php81-php-curl php81-php-devel php81-php-intl php81-php-ldap php81-php-pgsql php81-php-redis php81-php-uploadprogress php81-php-xdebug php81-php-zip php81-php-dom php81-php-odbc
    sudo dnf install -y php83 php83-php-cli php83-php-common php83-php-fpm php83-php-mysql php83-php-pdo php83-php-mbstring php83-php-gd php83-php-imagick php83-php-bcmath php83-php-curl php83-php-devel php83-php-intl php83-php-ldap php83-php-pgsql php83-php-redis php83-php-uploadprogress php83-php-xdebug php83-php-zip php83-php-dom php83-php-odbc

    php83 -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    sudo php83 composer-setup.php --install-dir=/usr/bin --filename=composer --2
    sudo php83 composer-setup.php --install-dir=/usr/bin --filename=composer2 --2
    sudo php83 composer-setup.php --install-dir=/usr/bin --filename=composer1 --1

    sudo chmod 775 -R /var/www/html && sudo chown vagrant:nginx -R /var/www/html
    mkdir -p /var/www/html/adminer && cd /var/www/html/adminer && wget https://github.com/vrana/adminer/releases/download/v4.8.1/adminer-4.8.1.php && mv adminer-4.8.1.php index.php
  SHELL
end
